name: Backend API Tests

on:
  pull_request:
    branches:
      - main
      - staging

jobs:
  tests:
    name: Run API Tests
    runs-on: ubuntu-latest
    env:
      secret_key: ${{ secrets.SECRET_KEY }}
      algorithm: ${{ secrets.ALGORITHM }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Detect Relevant Changes
        id: detect
        run: |
          git fetch --no-tags --prune --depth=1 origin ${{ github.base_ref }}
          CHANGED_FILES="$(git diff --name-only --diff-filter=AM HEAD origin/${{ github.base_ref }})"

          echo "Changed files:"
          echo "$CHANGED_FILES"

          # If any changed files match app/backend/app/ or scripts/test_api.sh, run tests;
          # otherwise skip them.
          if echo "$CHANGED_FILES" | grep -qE '^app/backend/app/|^scripts/test_api.sh$'; then
            echo "should_skip=false" >> "$GITHUB_OUTPUT"
          else
            echo "should_skip=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          pip install uv
          uv sync --group test --no-dev

      - name: Run API Tests
        run: |
          uv run bash scripts/test_api.sh
