name: Validate Markdown

on:
  pull_request_target:
    branches:
      - main
      - staging

permissions:
  contents: read
  pull-requests: write

jobs:
  detect-changes:
    name: Detect Changed Markdown/Notebook
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.detect.outputs.should_skip }}
    steps:
      - name: Checkout Base Repo (Safe Merge Commit)
        uses: actions/checkout@v4
        with:
          ref: refs/pull/${{ github.event.pull_request.number }}/merge

      - name: Detect .md or .ipynb Changes
        id: detect
        run: |
          git fetch --no-tags --prune --depth=1 origin ${{ github.base_ref }}
          CHANGED_FILES="$(git diff --name-only --diff-filter=AM origin/${{ github.base_ref }})"

          echo "Changed files:"
          echo "$CHANGED_FILES"

          if echo "$CHANGED_FILES" | grep -E '\.md$|\.ipynb$'; then
            echo "should_skip=false" >> "$GITHUB_OUTPUT"
          else
            echo "should_skip=true" >> "$GITHUB_OUTPUT"
          fi

  check-broken-paths:
    name: Check Broken Relative Paths
    runs-on: ubuntu-latest
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.should_skip == 'false' }}
    steps:
      - name: Checkout Base Repo (Safe Merge Commit)
        uses: actions/checkout@v4
        with:
          ref: refs/pull/${{ github.event.pull_request.number }}/merge
      - name: Check broken Paths
        id: check-broken-paths
        uses: john0isaac/action-check-markdown@v1.1.0
        with:
          command: check_broken_paths
          directory: ./
          guide-url: "https://github.com/0Upjh80d/agents/blob/main/CONTRIBUTING.md"
          github-token: ${{ secrets.GITHUB_TOKEN }}

  check-urls-locale:
    name: Check URLs Don't Have Locale
    runs-on: ubuntu-latest
    needs: [detect-changes, check-broken-paths]
    if: ${{ needs.detect-changes.outputs.should_skip == 'false' }}
    steps:
      - name: Checkout Base Repo (Safe Merge Commit)
        uses: actions/checkout@v4
        with:
          ref: refs/pull/${{ github.event.pull_request.number }}/merge
      - name: Run Check URLs Country Locale
        id: check-urls-locale
        uses: john0isaac/action-check-markdown@v1.1.0
        with:
          command: check_urls_locale
          directory: ./
          guide-url: "https://github.com/0Upjh80d/agents/blob/main/CONTRIBUTING.md"
          github-token: ${{ secrets.GITHUB_TOKEN }}

  check-broken-links:
    name: Check Broken Links
    runs-on: ubuntu-latest
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.should_skip == 'false' }}
    steps:
      - name: Checkout Base Repo (Safe Merge Commit)
        uses: actions/checkout@v4
        with:
          ref: refs/pull/${{ github.event.pull_request.number }}/merge
      - name: Run Linkspector
        uses: umbrelladocs/action-linkspector@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          fail_on_error: true
          config_file: .github/.linkspector.yml
          filter_mode: nofilter
