name: Validate Markdown

on:
  # Trigger the workflow on pull request
  pull_request_target:
    branches:
      - main
      - staging
    paths:
      - "**.md"
      - "**.ipynb"

permissions:
  contents: read
  pull-requests: write

jobs:
  check-broken-paths:
    name: Check Broken Relative Paths
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Check broken Paths
        id: check-broken-paths
        uses: john0isaac/action-check-markdown@v1.1.0
        with:
          command: check_broken_paths
          directory: ./
          guide-url: "https://github.com/0Upjh80d/agents/blob/main/CONTRIBUTING.md"
          github-token: ${{ secrets.GITHUB_TOKEN }}
  check-urls-locale:
    if: ${{ always() }}
    needs: check-broken-paths
    name: Check URLs Don't Have Locale
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Run Check URLs Country Locale
        id: check-urls-locale
        uses: john0isaac/action-check-markdown@v1.1.0
        with:
          command: check_urls_locale
          directory: ./
          guide-url: "https://github.com/0Upjh80d/agents/blob/main/CONTRIBUTING.md"
          github-token: ${{ secrets.GITHUB_TOKEN }}
  check-broken-links:
    name: Check Broken Links
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Run Linkspector
        uses: umbrelladocs/action-linkspector@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN  }}
          reporter: github-pr-review
          fail_on_error: true
          config_file: .github/.linkspector.yml
          filter_mode: nofilter # Runs check on all files instead of just changed files
